version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./src/frontend/"
    schedule:
      interval: "daily"
    labels:
      - npm
      - dependabot

  - package-ecosystem: "gomod"
    directory: "./src/backend/"
    schedule:
      interval: "daily"
    labels:
      - gomod
      - dependabot
