# https://rsbh.dev/blog/dockerize-react-app
FROM node:14-alpine

WORKDIR /app

COPY package.json ./

COPY yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

# EXPOSE 3000

CMD ["npm", "start"]