name: Frontend Helm Lint

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Helm Chart
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.19.11
          helm: 2.17.0
          helmv3: 3.6.0
          command: |
            helmv3 template ${{env.working-directory}}/charts/frontend | kubeval --strict --kubernetes-version 1.19.11 --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master
